name: 'IndexNow'
on:
  schedule:
    # Set the schedule time
    - cron: '0 2 * * *'

  # 저장소의 Actions 탭에서 수동으로 실행가능하게 하는 옵션
  workflow_dispatch:

jobs:
  check-and-submit:
    runs-on: ubuntu-latest
    steps:
      - name: indexnow-action
        uses: bojieyang/indexnow-action@v2
        with:
          sitemap-location: 'https://gitformike.github.io/sitemap_index.xml'
          key: ${{ secrets.INDEXNOW_KEY }}     
          endpoint: 'api.indexnow.org'
      - name: indexnow-action-bing
        uses: bojieyang/indexnow-action@v2
        with:
          sitemap-location: 'https://gitformike.github.io/sitemap_index.xml'
          key: ${{ secrets.INDEXNOW_KEY }}
          endpoint: 'www.bing.com'
      - name: indexnow-action-naver
        uses: bojieyang/indexnow-action@v2
        with:
          sitemap-location: 'https://gitformike.github.io/sitemap_index.xml'
          key: ${{ secrets.INDEXNOW_KEY }}     
          endpoint: 'searchadvisor.naver.com'   